# -*- coding: utf-8 -*-
"""golpista-2-0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/edifesf1/f690ec677422ea5e5309c84556ba4697/golpista-2-0.ipynb
"""

#Ligação
!pip install --upgrade gspread
!pip install pytelegrambotapi

#Cabeçalho
import telebot
import time
import csv
import time
from datetime import datetime
from google.colab import auth
import gspread
from google.auth import default
#import panda
import pandas as pd

#token
token = '6262749672:AAE4hiAkl8yBvtLaIuXRtmWBZO_oTGVGyNk'
bot = telebot.TeleBot(token)

#Credenciais google sheet
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

#Panda Importar dados para bd pandas
golpistapd = pd.DataFrame(page.get_all_records())

golpistapd.head()

#------------------ FUNÇÕES ----------------------------------
#Verifica se chegou mensagem
def verificar(mensagem):
  return True

#Achar tamanho do numero
def achaTamanho(numero):
    numero = abs(int(numero))
    if numero < 2:
        return 1
    count = 0
    valor = 1
    while valor <= numero:
        valor *= 10
        count += 1
    return count

#MenuPrincipal
def menu1(message):
    texto = """
  Clique em uma opção:
  /opcao1 Verificar_Numero .
  /opcao2 Inserir_Numero ."""
    global var1
    var1 = "0"
    bot.reply_to(message, texto)

#Criar var1
var1 = "0"

def resetvar1():
  global var1
  var1 = "0"

#variavel armazena o documento
spreasheet = gc.open('Golpista')

#Seleciona primeira planilha
page = spreasheet.sheet1

#mostra valores
page.col_values(1)
page.row_values(1)
page.acell('C5').value
page.cell(2,2).value

#inserir dados
page.update('B2','2b')
page.cell(2,2).value

#Opção 1
@bot.message_handler(commands=["opcao1"])
def opcao1(message):
  global var1
  var1 = "1"
  bot.send_message(message.chat.id,"Consultar",timeout=120)

#Opção 2
@bot.message_handler(commands=["opcao2"])
def opcao2(message):
  global var1
  var1 = "2"
  bot.send_message(message.chat.id,"Inserir",timeout=120)

#Pesquisa funciona
def pesquisa1(m1,message):
  fone1 = m1
  message = message
  bot.send_message(message.chat.id,"voce digitiou ",timeout=120)
  bot.send_message(message.chat.id,m1,timeout=120)
  #var3 = golpistapd["qtn"]==m1
  bot.send_message(message.chat.id,var3,timeout=120)
  global var1
  var1 = "0"

#Chama a função verificar mensagem e abre o meunu principal
@bot.message_handler(func=verificar)
def principal1(message):
  if var1 != "0":
    message = message
    m1 = message.text
    m1 = m1.replace(" ", "")
    m1 = m1.replace("-", "")
    bot.send_message(message.chat.id,"Diferente de zero",timeout=120)
    if m1.isdigit():
      if var1 == "1":
        bot.send_message(message.chat.id,"var1",timeout=120)
        pesquisa1(m1,message)
      if var1 == "2":
        bot.send_message(message.chat.id,"var2",timeout=120)
        pesquisa1(m1,message)
    else:
      bot.send_message(message.chat.id,"Numero Invalido, Digite o Número em um dos formatos Abaixo",timeout=60)
      bot.send_message(message.chat.id,"DDD + 9 + numero nesse formato: 31 9 8888 7777",timeout=60)
      bot.send_message(message.chat.id,"DDD + numero nesse formato: 31 8888 7777",timeout=60)
      resetvar1()
  menu1(message)

#Rodape
bot.polling()